import {
  Building2,
  BarChart3,
  Sparkles,
  Target,
  ClipboardList,
  Radio,
  Search,
  TrendingUp,
  ShieldCheck,
  Zap,
  Flame,
  Bug,
  CheckCircle2,
  Brain,
  Shield,
  Activity,
  BookOpen,
  HardDrive,
  FileSearch,
  Monitor,
  Bell,
  Gauge,
  Network,
  Megaphone,
  Workflow,
  GitBranch,
  RefreshCw,
  Binary,
  Cpu,
  type LucideIcon,
} from 'lucide-react'

// ─── Lucide icon map — SVG icons only, no Unicode emojis ──────────────────────

export const AVATAR_ICONS: Record<string, LucideIcon> = {
  'building-2': Building2,
  'bar-chart-3': BarChart3,
  'sparkles': Sparkles,
  'target': Target,
  'clipboard-list': ClipboardList,
  'radio': Radio,
  'search': Search,
  'trending-up': TrendingUp,
  'shield-check': ShieldCheck,
  'zap': Zap,
  'flame': Flame,
  'bug': Bug,
  'check-circle': CheckCircle2,
  'brain': Brain,
  'shield': Shield,
  'activity': Activity,
  'book-open': BookOpen,
  'hard-drive': HardDrive,
  'file-search': FileSearch,
  'monitor': Monitor,
  'bell': Bell,
  'gauge': Gauge,
  'network': Network,
  'megaphone': Megaphone,
  'workflow': Workflow,
  'git-branch': GitBranch,
  'refresh-ccw': RefreshCw,
  'binary': Binary,
  'cpu': Cpu,
}
